### ISSUE TITLE
Localize whole application

### ISSUE THREAD

**Issue by skddc** [skddc/webmarks#12]
Maybe these could be helpful:
- https://hacks.mozilla.org/2014/01/localizing-the-firefox-os-boilerplate-app

**Comment by galfert** [comment]
Ember addon for internationalization: https://github.com/jamesarosen/ember-i18n

**Comment by galfert** [comment]
In a different project I determined the locale using the user's preferred Browser languages.

Using an instance initializer (`app/instance-initializers/i18n`):

```javascript
export default {
  name: 'i18n',

  initialize: function(application) {
    let i18n = application.lookup('service:i18n');
    i18n.set('locale', determineLocale(i18n.get('locales')));
  }
};

function determineLocale(availableLocales) {
  let userLanguages = navigator.languages || [];
  userLanguages.push(navigator.language, navigator.userLanguage, 'en');

  return userLanguages.compact().find((language) => {
    return availableLocales.indexOf(language) > -1 ||
           availableLocales.indexOf(language.split('-')[0]) > -1;
  });
}
```

**Comment by skddc** [comment]
Works great now! I'm merging locally, with some changes on top.
