### ISSUE TITLE
Confirmation to delete

### ISSUE THREAD

**Issue by benrubson** [skddc/webmarks#41]
Hello,

Would be nice to have a confirmation request before deleting a bookmark.

Thank you !

Ben

**Comment by skddc** [comment]
Alternative options:

* Undo
* hold-to-delete (2 seconds or so)

**Comment by galfert** [comment]
I like the undo idea.

**Comment by benrubson** [comment]
Hi,
Do you have some news regarding this feature request ?
Deleting bookmarks by mistake can be easy, especially from smartphones (I experienced it) :-/
Not sure the "undo" is the way to go, especially if you think about smartphones.
IMO, a confirmation, or a long click, would be better.
Thank you very much 👍

**Comment by skddc** [comment]
Sorry, no update yet. But I'm going to look at this very soon, likely during SHA2017, so between this Thursday and next Wednesday.

**Comment by benrubson** [comment]
Many thx Sebastian 👍

**Comment by skddc** [comment]
The delete button has moved to the edit form in the latest version. Not deployed just yet, but end of the day latest.
