### ISSUE TITLE
Webmarks seems to like memory

### ISSUE THREAD

**Issue by benrubson** [skddc/webmarks#44]
Hello,

Webmarks eats a lot of memory :

![screen shot 2016-12-27 at 09 18 30](https://cloud.githubusercontent.com/assets/6764151/21495026/92ef610c-cc15-11e6-911c-dc9de7969fb5.png)

Thank you !

Ben

**Comment by skddc** [comment]
I see normal usage (same as e.g. DuckDuckGo) in both Chrome and FF.

How long has it been running in that tab? And which browser is that?

**Comment by benrubson** [comment]
Mac OS / Safari 10.0.2.

Firs time I saw this is when I added a lot of bookmarks (around 100), it took a lot of memory quite quickly.
This time it was without adding bookmarks, tab has been running for around 2 days.
If I close the tab an open it again, memory usage is then OK.
But I expect it to grow again, I keep an eye on it.

**Comment by skddc** [comment]
Ok, thanks. Looks like it's leaking memory over time then.

**Comment by benrubson** [comment]
I'm still experiencing the issue.
As soon as there is activity on the page, memory usage is growing.

For example, using search field several times in a row, we clearly see memory usage growing quite fast.

Were you able to reproduce this issue ?

Many thx 👍

**Comment by skddc** [comment]
I haven't looked into this yet. Personally, I never leave the app open for longer than storing a bookmark or looking one up, so it's not high on my personal priority list. If someone else could investigate, that'd be much appreciated!

**Comment by benrubson** [comment]
Some news, still facing the issue, with Safari 11.1.
Thx !

**Comment by skddc** [comment]
I believe this would have been caused by some bug in an older version of Ember. I left the app open over night with the current, much newer version, and it didn't add a single MB in memory usage. Feel free to open a new issue in case it happens again. Thanks.
