### ISSUE TITLE
Error when autocompleting tag with TAB

### ISSUE THREAD

**Issue by galfert** [skddc/webmarks#47]
When hitting TAB to autocomplete a tag, the following error is thrown:

`Uncaught TypeError: Cannot read property 'menu' of undefined`

Error is happening in this line: https://github.com/skddc/webmarks/blob/6727e97d124ad44e771bc8b2dd14cdeb22958af0/app/components/bookmark-form/component.js#L21

I thought I tested tab completion when reviewing the PR, but I'm not sure yet if I only used ENTER.

**Comment by skddc** [comment]
Thanks.
