### ISSUE TITLE
Select text in search field

### ISSUE THREAD

**Issue by benrubson** [skddc/webmarks#52]
Hello,

This feature request follows #46.
Would be nice for the text (inside the search field) to be selected when the search field is focused.
So that we can then search for something else very quickly when we come back to the Webmarks page.

Many thx 👍 

Ben

**Comment by benrubson** [comment]
Hi,

Some news regarding this tiny feature request ? :)

Thank you again 👍 

Ben

**Comment by skddc** [comment]
Thanks for your request, Ben! Are you talking about mobile or desktop usage? I'm not a fan of JavaScript getting in the way of standard UI behavior, so on desktop I'd prefer to have the user select the text themselves in case they want to replace it.

However, on mobile it's not so easy to select text, so the usual way to clear a search field is a delete (x) button on the right hand side. I think this could be useful for sure.

**Comment by benrubson** [comment]
Thank you for your answer Sebastian !
I'm talking about desktop usage :)
This request follows #46 where search field is now re-focused after something has been clicked.
This of course improves user experience, speeds up Webmarks usage.

I then think it could even be better if, when there is some text inside the search field, in addition for the field to be focused, the text could also be selected.
So that the user can type something new without having to first clear the field.

Of course I think this requires some JS (`select()` function I think).

**Comment by skddc** [comment]
I'll check it out.

**Comment by benrubson** [comment]
Some news regarding this ? :)
Many thanks !

**Comment by skddc** [comment]
No news. Last thing I did was updating the underlying framework and all code. I'll have a go at this one next.

**Comment by benrubson** [comment]
OK, thank you Sebastian 👍

**Comment by skddc** [comment]
I just deployed a new version, which shows a button for clearing the search field when it contains text. This should solve it nicely on both mobile and desktop. (It will also keep/re-set the focus on the field when clicking it.)

**Comment by benrubson** [comment]
Thank you Sebastian 👍 

Use case was also the following : you search for a bookmark, click on it, read this new opened page.
You come back to Webmarks and want to search for another bookmark.
It would then be nice for the previous searched text to be selected, so that you can enter new text directly without having to click / select or whatever.
Do you see why I would have liked the text to be selected ?

**Comment by benrubson** [comment]
Understood, thank you for your feedback Sebastian 👍
