### ISSUE TITLE
Translate to more languages

### ISSUE THREAD

**Issue by raucao** [skddc/webmarks#73]
This one's easy: just take the translation strings in `app/locales/XX/translations.js` and port them to languages you know. The only language in addition to English right now is German.

@gregkare @hugoroy Want to help me with French? :)
@lesion How about Italian?
@michielbdejong @fkooman Dutch translation perhaps?

Edit: I added [translation info](https://github.com/skddc/webmarks#translations) to the README, including some instructions for adding new ones.

(Ideally this should be accompanied by [widget i18n](https://github.com/remotestorage/remotestorage-widget/issues/42) as well, of course.)

**Comment by gregkare** [comment]
I gave it a shot: #74. @hugoroy, could you review it?

I found a hardcoded string:

```
app/components/bookmark-saved/template.hbs
7:    {{#link-to "archive.index" class="button button-secondary"}}Back to list{{/link-to}}
```

Also the `welcome_page` section is not used anymore in the current version

**Comment by skddc** [comment]
> I found a hardcoded string:
> Also the `welcome_page` section is not used anymore in the current version

Fixing both. Thanks for reporting.

**Comment by hugoroy** [comment]
Hey! Yes, I'll have a look :-)

**Comment by skddc** [comment]
@hugoroy Did you have a chance to check it out?

**Comment by skddc** [comment]
Closing this for now, with the info added to README and another language supported.
