### ISSUE TITLE
Getting error when trying to connect Dropbox or GDrive

### ISSUE THREAD

**Issue by galfert** [skddc/webmarks#76]
Both backends show an error page about the `redirect_uri` being invalid.

Needs to have (at least) https://webmarks.5apps.com/archive and https://webmarks.5apps.com/archive/new configured.

**Comment by skddc** [comment]
Oh damn. Good catch. I changed the URLs.

**Comment by skddc** [comment]
They should both work now.

However, I already found an issue with Dropbox. The initial sync is stuck on the loading screen for me. Have to reload to see the bookmarks.

**Comment by skddc** [comment]
Found the problem. The `getAll()` was attempted before remoteStorage was ready.
