### ISSUE TITLE
Make layout responsive/usable on mobiles

### ISSUE THREAD

**Issue by skddc** [skddc/webmarks#8]

**Comment by benrubson** [comment]
Hello,
@skddc, any news regarding this feature ?
Many thx 👍

**Comment by skddc** [comment]
Not exactly about this feature, but we just did a big upgrade from a very old build system and Ember.js version to the latest and greatest stuff. So now we have a proper basis for improving the app and adding new features.

I'm actually planning to look at this soon.

**Comment by skddc** [comment]
Basic support for small screens has just been deployed! Feedback welcome.

This is just the beginning, and also comes after a slew of other improvements. Stay tuned.

**Comment by skddc** [comment]
I'm glad to report that Webmarks is now properly usable on mobile devices. Next up is #38.

Feedback welcome!
